spring:
  application:
    name: SpringSecurityPractice
    
  jpa:
    hibernate:
      ddl-auto: create
    
    show-sql: true  

  datasource:
    url: jdbc:mysql://localhost:3306/spring_practice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ketan.rauniyar305@gmail.com
    password: jbxm ulur apsg tdcj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true